###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [ ]:
import numpy as np

matrix = np.random.randint(0, 101, (3, 4))
print("Original Matrix:\n", matrix)

# i. Sort this matrix using np.sort()
sorted_matrix = np.sort(matrix, axis=1)
print("\nMatrix sorted row-wise (each row is sorted individually):\n", sorted_matrix)

# ii. Sort this matrix based on values in the 2nd column
sorted_by_second_column = matrix[matrix[:, 1].argsort()]
print("\nMatrix sorted based on values in the 2nd column:\n", sorted_by_second_column)

# iii. Sort this matrix based on the max value in each row
sorted_by_row_max = matrix[np.max(matrix, axis=1).argsort()]
print("\nMatrix sorted based on max value in each row:\n", sorted_by_row_max)

# iv. Sort based on elements value
sorted_by_elements = np.sort(matrix, axis=None).reshape(3, 4)
print("\nMatrix sorted by all elements (flattened and sorted):\n", sorted_by_elements)

Original Matrix:
 [[36 35 14 18]
 [ 3 48 79 57]
 [ 9 19  2 28]]

Matrix sorted row-wise (each row is sorted individually):
 [[14 18 35 36]
 [ 3 48 57 79]
 [ 2  9 19 28]]

Matrix sorted based on values in the 2nd column:
 [[ 9 19  2 28]
 [36 35 14 18]
 [ 3 48 79 57]]

Matrix sorted based on max value in each row:
 [[ 9 19  2 28]
 [36 35 14 18]
 [ 3 48 79 57]]

Matrix sorted by all elements (flattened and sorted):
 [[ 2  3  9 14]
 [18 19 28 35]
 [36 48 57 79]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [1]:
import numpy as np

# Given data
marks = np.array([
    [13, 10,  9, 33],
    [63, 46, 90, 42],
    [39, 76, 13, 29],
    [82,  9, 29, 78],
    [67, 61, 59, 36]
])

extra_subject = np.array([41, 87, 72, 36, 92])
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

# Task i: Add marks of an extra subject
marks_with_extra_subject = np.column_stack((marks, extra_subject))
print("Marks with extra subject added:\n", marks_with_extra_subject)

# Task ii: Add two new students
new_students = np.array([rec1, rec2])
marks_with_new_students = np.vstack((marks_with_extra_subject, new_students))
print("\nMarks with new students added:\n", marks_with_new_students)

# Task iii: Add extra column with sum of all subjects marks
total_marks = np.sum(marks_with_new_students, axis=1)
marks_with_totals = np.column_stack((marks_with_new_students, total_marks))
print("\nMarks with total marks column added:\n", marks_with_totals)

# Task iv: Sort the array based on total marks and show top 2 rows
sorted_marks = marks_with_totals[marks_with_totals[:, -1].argsort()[::-1]]
top_2_students = sorted_marks[:2]
print("\nTop 2 students based on total marks:\n", top_2_students)


Marks with extra subject added:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

Marks with new students added:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]

Marks with total marks column added:
 [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]

Top 2 students based on total marks:
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [2]:
import numpy as np

arr = np.array([
    [1, 2, 3, 3, 1, 1],
    [0, 9, 1, 2, 8, 8],
    [1, 2, 3, 8, 8, 8],
    [1, 2, 3, 3, 1, 1]
])

# Finding unique rows
unique_rows = np.unique(arr, axis=0)
print("Unique Rows:\n", unique_rows)

# Finding unique columns
unique_columns = np.unique(arr.T, axis=0).T
print("\nUnique Columns:\n", unique_columns)


Unique Rows:
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Unique Columns:
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [4]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Flip the array along both axes
flipped_array = np.flip(arr, axis=(0, 1))

print(arr)
print("\nFlipped Array along both axes:\n", flipped_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Flipped Array along both axes:
 [[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [5]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [10, -3, 30, 4, 5],
    [3, 2, 5, -4, 5],
    [9, 7, 3, 6, 5]
])

X = 6

row_numbers = np.where(np.any(arr > X, axis=1))[0]
print(row_numbers)

[1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [7]:
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)

flat_array = np.concatenate((arr1, arr2, arr3))

print(flat_array)

[0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [9]:
import numpy as np

# Set seed and create the array
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

# Find the minimum and maximum elements in the array
min_val = np.min(arr)
max_val = np.max(arr)

print(f"Minimum value in the array: {min_val}")
print(f"Maximum value in the array: {max_val}")

# Remove the minimum and maximum elements from the array
arr_without_min_max = arr[arr != min_val]
arr_without_min_max = arr_without_min_max[arr_without_min_max != max_val]

print("\nArray after removing minimum and maximum values:\n", arr_without_min_max)


Minimum value in the array: 103
Maximum value in the array: 998

Array after removing minimum and maximum values:
 [448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
 353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
 921 490 527 972 278 307 840 958 246 449 251 957 627 920 824 356 825 173
 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211 771
 270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922 967
 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325 729
 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395 525
 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618 226
 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291 194
 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883 588]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [10]:
import numpy as np

arr = np.array([150, 250, 120, 180, 300, 90, 210, 700])

# Step 1: Limit the array's elements between 100 and 200
arr = np.clip(arr, 100, 200)

print("Array after limiting values between 100 and 200:\n", arr)

# Step 2: Sort the array
arr_sorted = np.sort(arr)

print("\nSorted Array:\n", arr_sorted)

# Step 3: Perform the cumulative sum of the sorted array
cumulative_sum = np.cumsum(arr_sorted)

print("\nCumulative Sum of the Sorted Array:\n", cumulative_sum)

Array after limiting values between 100 and 200:
 [150 200 120 180 200 100 200 200]

Sorted Array:
 [100 120 150 180 200 200 200 200]

Cumulative Sum of the Sorted Array:
 [ 100  220  370  550  750  950 1150 1350]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [13]:
import numpy as np

arr = np.random.rand(10)

# Step 1: Round off the elements to 3 decimal places
arr_rounded = np.round(arr, 3)
print("Array after rounding to 3 decimal places:\n", arr_rounded)

# Step 2: Compare 0th percentile with minimum value and 100th percentile with maximum value
min_value = np.min(arr_rounded)
max_value = np.max(arr_rounded)

percentile_0th = np.percentile(arr_rounded, 0)
percentile_100th = np.percentile(arr_rounded, 100)

print("\n0th percentile:", percentile_0th)
print("Minimum value:", min_value)
print("0th percentile == Minimum value:", percentile_0th == min_value)

print("\n100th percentile:", percentile_100th)
print("Maximum value:", max_value)
print("100th percentile == Maximum value:", percentile_100th == max_value)

# Step 3: Find the difference between 51st percentile and 50th percentile values
percentile_50th = np.percentile(arr_rounded, 50)
percentile_51st = np.percentile(arr_rounded, 51)

difference = percentile_51st - percentile_50th
print("\n50th percentile value:", percentile_50th)
print("51st percentile value:", percentile_51st)
print("Difference between 51st and 50th percentiles:", difference)

Array after rounding to 3 decimal places:
 [0.974 0.4   0.696 0.776 0.484 0.204 0.536 0.082 0.63  0.206]

0th percentile: 0.082
Minimum value: 0.082
0th percentile == Minimum value: True

100th percentile: 0.974
Maximum value: 0.974
100th percentile == Maximum value: True

50th percentile value: 0.51
51st percentile value: 0.51468
Difference between 51st and 50th percentiles: 0.0046800000000000175
