**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [4]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [4]:
vect = np.zeros(10, dtype=np.int32)
vect[4] = 1
print(vect)

[0 0 0 0 1 0 0 0 0 0]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [8]:
user_input = input('Enter two numbers separated by space: ').split()
a, b = map(int, user_input)
arr = np.random.random((a, b))
print(arr)
print(np.mean(arr))

Enter two numbers separated by space: 2 3
[[0.36037785 0.43607693 0.35215509]
 [0.75584516 0.00997594 0.61825963]]
0.4221150974912889


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [12]:
def create_border_array(a, b):
    arr = np.ones((a, b), dtype=int)
    arr[1:-1, 1:-1] = 0
    return arr

create_border_array(4, 4)

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [13]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [14]:
matrix = np.eye(3, 4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [15]:
matrix = np.zeros((5, 5), dtype=int)
matrix += np.arange(5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [16]:
vector = np.random.randint(1, 101, size=(10, 2))
point = np.array([2, 3])
distances = np.sqrt(np.sum((vector - point) ** 2, axis=1)).astype(int)
print(distances)

[ 86  66  85 110  27 117  39  52  50  48]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [17]:
tensor = np.zeros((6, 7, 8))
index = np.unravel_index(100, tensor.shape)
print(index)

(1, 5, 4)


In [18]:
index = np.unravel_index(100, (6, 7, 8))
index

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [19]:
user_input = input('Enter space separated numbers: ').split()
arr = np.array(user_input, dtype=float)[::-1]
print(arr)

Enter space separated numbers: 1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [20]:
user_input = input('Enter space separated numbers: ').split()
maping = map(float, user_input)
arr = np.array(list(maping))[::-1]
print(arr)

Enter space separated numbers: 1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [21]:
user_input = input('Enter space separated numbers: ').split()
arr = np.array(user_input, dtype=int)
print(f'elements_count : {arr.size}')

Enter space separated numbers: 1 2 4 5 6 7
elements_count : 6


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [25]:
def softmax(arr):
    if isinstance(arr, np.ndarray) and arr.ndim == 1:
        exp_arr = np.exp(arr)
        return exp_arr / np.sum(exp_arr)
    else:
        raise ValueError('Input must be a 1D numpy array')

user_input = input('Enter space separated numbers: ').split()
arr = np.array(user_input, dtype=float)
print(softmax(arr))

Enter space separated numbers: 33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278
[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [28]:
a = [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]]

b = [[1, 1, 1, 1, 1],
     [1, 1, 1, 1, 1]]

stack = np.vstack((a, b))
print(stack)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [31]:
def vertical_stack(*arrays):
    for array in arrays:
        if not isinstance(array, np.ndarray):
            raise TypeError("All inputs must be numpy arrays")
    if len(arrays) == 0:
        raise ValueError("At least one input array is required")
    return np.vstack(arrays)

a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
c = np.array([[0.10117373, 0.1677244, 0.73764059, 0.83166097, 0.48985695],
              [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

result = vertical_stack(a, b, c)
print(result)


[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [33]:
import numpy as np

def date_array(start, end):
    if not (isinstance(start, str) and isinstance(end, str)):
        raise TypeError("Both inputs must be strings")
    date_format = "%Y-%m-%d"

    try:
        start_date = np.datetime64(start)
        end_date = np.datetime64(end)
    except ValueError:
        raise ValueError("Dates should be in the format YYYY-MM-DD")

    dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), dtype='datetime64[D]')
    return dates

result = date_array('2020-11-25', '2020-11-30')
print(result)

['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [34]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_means = np.mean(matrix, axis=1, keepdims=True)
result = matrix - row_means
print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [35]:
# col1 = np.array([1, 2, 3])
# col2 = np.array([4, 5, 6])
# arr = np.column_stack((col2, col1))
# print(arr)

[[4 1]
 [5 2]
 [6 3]]


In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[:, [0, 1]] = arr[:, [1, 0]]
print(arr)

[[2 1 3]
 [5 4 6]
 [8 7 9]]


###`Q-16:` Replace odd elements in arrays with -1.

In [37]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array[array % 2 == 1] = -1
print(array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [40]:
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])
result = np.maximum(a, b)
print(result)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [41]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[7636, 9574, 6212, 9613, 7041],
       [8389, 4889, 9472, 9797, 5196],
       [8479, 1870, 9180, 6380, 1578],
       [8693, 5052, 2526, 5423,  732],
       [8457, 7331,  449, 9368, 9604],
       [2280, 1399, 2867, 4141, 7739],
       [1445, 2246, 3799, 5244, 9964],
       [ 190, 3187, 2140, 5379, 2484]])

In [42]:
array = arr1[:, ::2]
print(array)

[[7636 6212 7041]
 [8389 9472 5196]
 [8479 9180 1578]
 [8693 2526  732]
 [8457  449 9604]
 [2280 2867 7739]
 [1445 3799 9964]
 [ 190 2140 2484]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [44]:
def find_nth_largest(arr, n):
    if n > len(arr):
        raise ValueError("n should be less than or equal to the length of the array")
    sorted_arr = np.sort(arr)
    return sorted_arr[-n]

arr = np.array([12, 34, 40, 7, 1, 0])
n = 3
result = find_nth_largest(arr, n)
print(result)

12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [45]:
a = np.array([1, 2, 3])
pattern = np.concatenate([np.repeat(a, 3), a, a, a])
print(pattern)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
